packages:
  - 'packages/*'

overrides:
  '@eslint-community/eslint-utils': ^4.6.1
  '@typescript-eslint/utils': ^8.30.1
  eslint: ^9.24.0
  tsx: ^4.19.3

catalogs:
  dev:
    '@esbuild/darwin-arm64': ^0.25.2
    '@eslint/config-inspector': ^1.0.2
    '@stylistic/eslint-plugin-migrate': ^4.2.0
    '@types/lodash.merge': ^4.6.9
    '@types/node': ^22.14.1
    '@types/semver': ^7.7.0
    '@typescript-eslint/rule-tester': ^8.30.1
    '@typescript-eslint/typescript-estree': ^8.30.1
    '@typescript-eslint/utils': ^8.30.1
    ajv: ^8.17.1
    bumpp: ^10.1.0
    eslint-typegen: ^2.1.0
    eslint-vitest-rule-tester: ^1.1.0
    esno: ^4.8.0
    execa: ^9.5.2
    find-up-simple: ^1.0.1
    jiti: ^2.4.2
    lint-staged: ^15.5.1
    lodash.merge: 4.6.2
    pnpm-workspace-yaml: ^0.3.1
    semver: ^7.7.1
    simple-git-hooks: ^2.12.1
    tinyglobby: ^0.2.12
    tsup: ^8.4.0
    tsx: ^4.19.3
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vitest: ^3.1.1

  peer:
    '@eslint-react/eslint-plugin': ^1.48.3
    '@prettier/plugin-xml': ^3.4.1
    '@unocss/eslint-plugin': ^66.0.0
    eslint: ^9.24.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.19
    eslint-plugin-vuejs-accessibility: ^2.4.1

  prod:
    '@antfu/install-pkg': ^1.0.0
    '@clack/prompts': ^0.10.1
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/compat': ^1.2.8
    '@eslint/markdown': ^6.3.0
    '@stylistic/eslint-plugin': ^4.2.0
    '@typescript-eslint/eslint-plugin': ^8.30.1
    '@typescript-eslint/parser': ^8.30.1
    '@vitest/eslint-plugin': ^1.1.42
    ansis: ^3.17.0
    cac: ^6.7.14
    eslint-flat-config-utils: ^2.0.1
    eslint-merge-processors: ^2.0.0
    eslint-plugin-command: ^3.2.0
    eslint-plugin-import-x: ^4.10.5
    eslint-plugin-jsdoc: ^50.6.9
    eslint-plugin-jsonc: ^2.20.0
    eslint-plugin-n: ^17.17.0
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.11.0
    eslint-plugin-pnpm: ^0.3.1
    eslint-plugin-regexp: ^2.7.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^57.0.0
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-vue: ^10.0.0
    eslint-plugin-yml: ^1.17.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.0.0
    jsonc-eslint-parser: ^2.4.0
    local-pkg: ^1.1.1
    parse-gitignore: ^2.0.0
    toml-eslint-parser: ^0.10.0
    vue-eslint-parser: ^10.1.3
    yaml-eslint-parser: ^1.3.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
